gestor/urls.py
from django.urls import path
from .views import Home, Visaogeral, Geral, Pesquisa, Painel, Backlog, Detalhependencia, Vencidos, Atrasados, Mudarstatus, Criarpend, Addcusto
from django.contrib.auth import views as auth_view

app_name = 'gestor'

urlpatterns = [

    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('', Home.as_view(), name='home'),
    path('gestor/', Visaogeral.as_view(), name='visualizarpendencia'),
    path('gestor/geral/', Geral.as_view(), name='geral'),
    path('gestor/geral/pesquisa/', Pesquisa.as_view(), name='pesquisa'),
    path('gestor/painel/', Painel.as_view(), name='painel'),
    path('visualizar/backlogs/recentes', Backlog.as_view(), name='backlog'),
    path('visualizar/backlogs/recentes/<int:pk>', Detalhependencia.as_view(), name='detalhependencia'),
    path('visualizar/backlogs/recentes/<int:pk>/update', Mudarstatus.as_view(), name='mudarstatus'),
    path('visualizar/backlogs/vencidos', Vencidos.as_view(), name='vencidos'),
    path('visualizar/backlogs/antigos', Atrasados.as_view(), name='atrasados'),
    path('visualizar/backlogs/novo', Criarpend.as_view(), name='criarpend'),
    path('visualizar/backlogs/addcusto', Addcusto.as_view(), name='addcusto'),
  
    
]

mantenedor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestor.urls', namespace='gestor')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestor/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

LISTA_CATEGORIA = (
    ("maquina base", "Maquina Base"),
    ("cabecote", "Cabeça Processadora"),
)

LISTA_SIM_NAO = (
    ('sim', 'Sim'),
    ('nao', 'Não'),
)
LISTA_STATUS = (
    ('no prazo', 'No prazo'),
    ('vencido', 'Vencido'),
    ('concluido', 'Concluido'),
)

LISTA_MAQUINAS = (
    ('F-HVE-0339', 'F-HVE-0339'),
    ('F-HVE-0341', 'F-HVE-0341'),
    ('F-HVE-0343', 'F-HVE-0343'),
    ('F-HVE-0347', 'F-HVE-0347'),
    ('F-HVE-0539', 'F-HVE-0539'),
    ('F-HVE-0540', 'F-HVE-0540'),
    ('F-HVE-0541', 'F-HVE-0541'),
    ('F-HVE-0542', 'F-HVE-0542'),
    ('F-HVE-0543', 'F-HVE-0543'),
    ('F-HVE-0544', 'F-HVE-0544'),
)

LISTA_LETRAS = (
    ('Letra A', 'Letra A'),
    ('Letra B', 'Letra B'),
    ('Letra C', 'Letra C'),
    ('Letra D', 'Letra D'),
)

class Instancia (models.Model):
    modulo = models.CharField(max_length=100)
    empresa = models.CharField(max_length=100)

    def __str__(self):
        return self.modulo

class Equipamentos_maq (models.Model):
    tag = models.CharField(max_length=50)
    horas_motor = models.CharField('Horimetro:', max_length=50)
    imagem_maquina = models.ImageField(upload_to='thumb_maquinas')
    modulo = models.ForeignKey("Instancia", related_name='maquinas', on_delete=models.CASCADE )
    padrinho = models.CharField(max_length=80, choices=LISTA_LETRAS, default='Letra A')
    
    def __str__(self):
        return self.tag

class Pendencias (models.Model):

    maquina = models.ForeignKey("Equipamentos_maq", related_name='pendencias', on_delete=models.CASCADE)
    list_maquina = models.CharField('Repita a Maquina Selecionada:', max_length=50, choices=LISTA_MAQUINAS, default='Selecione')
    categoria = models.CharField(max_length=50, choices=LISTA_CATEGORIA)
    titulo = models.CharField(max_length=50)
    corpo = models.TextField(max_length=1000)
    data_criacao = models.DateTimeField('Data de Criação',default=timezone.now)
    tempo_hora_homem = models.FloatField('Tempo Estimado de Manutenção (HH)',max_length=100, default=1.0)
    status = models.CharField(max_length=100, choices=LISTA_STATUS)
    thumb = models.ImageField('Foto da Pendencia:', upload_to='thumb_pendencias', default='default.jpg')

    def __int__(self):
        return self.pk


class Custo (models.Model):
    backlog = models.ForeignKey("Pendencias", on_delete=models.CASCADE, related_name='materiais', null=True, default=1)
    codigo = models.CharField(max_length=100)
    ni = models.CharField(max_length=100)
    item = models.CharField(max_length=100)  
    qtd = models.IntegerField()
    preco_unit = models.FloatField(max_length=100)
    
    def __str__(self):
        return  self.item

gestor/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Equipamentos_maq, Pendencias, Custo
from django.urls import reverse


# Create your views here.
class Home(TemplateView):
    template_name = 'home.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('gestor:geral')        
        else:
            return super().get( request, *args, **kwargs)

class Visaogeral(LoginRequiredMixin, TemplateView):
    template_name = "visualizapendencias.html"

class Geral(LoginRequiredMixin, ListView):
    template_name = 'geral.html'
    model = Equipamentos_maq

class Pesquisa(LoginRequiredMixin, ListView):
    template_name = 'pesquisa.html'
    model = Equipamentos_maq
    
    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('q')
        if termo_pesquisa:
            object_list = self.model.objects.filter(tag__icontains= termo_pesquisa)
            return object_list
        else:
            return None

class Painel(LoginRequiredMixin, TemplateView):
    template_name = 'painel.html'

class Backlog(LoginRequiredMixin, ListView):
    template_name = 'recentes.html'
    model = Pendencias

class Detalhependencia(LoginRequiredMixin, DetailView):
    template_name = "detalhespendencias.html"
    model = Pendencias
    
    def get_context_data(self, **kwargs):
        context = super(Detalhependencia, self).get_context_data(**kwargs)
        pendencias_relacionadas = Pendencias.objects.filter(list_maquina=self.get_object().list_maquina)
        context['pendencias_relacionadas'] = pendencias_relacionadas
        return context

class Mudarstatus (LoginRequiredMixin, UpdateView):
    template_name = 'mudstatus.html'
    model = Pendencias
    fields = ['status']
    
    def get_success_url(self):
        return reverse('gestor:backlog')
    
     
class Atrasados(LoginRequiredMixin, ListView):
    template_name = 'atrasados.html'
    model = Pendencias

class Vencidos(LoginRequiredMixin, ListView):
    template_name = 'vencidos.html'
    model = Pendencias

class Criarpend (LoginRequiredMixin, CreateView):
    template_name = "criarpend.html"
    model = Pendencias
    fields = ['maquina', 'list_maquina', 'categoria', 'titulo', 'corpo', 'data_criacao', 'tempo_hora_homem', 'status', 'thumb' ]
    
    def get_success_url(self):
        return reverse('gestor:backlog')

class Addcusto (LoginRequiredMixin, CreateView):
    template_name = "addcusto.html"
    model = Custo
    fields = ['backlog', 'codigo', 'ni', 'item', 'qtd', 'preco_unit' ]
    
    def get_success_url(self):
        return reverse('gestor:geral')


   

gestor/templates/atrasados.html
{% extends 'visualizapendencias.html' %}

{% block pendencias %}
<style>
    #alvo {
        display: flex;
        flex-wrap: nowrap;
        overflow-x: scroll;
        width: 1200px;
      }   
</style>
<div class="container">
    <br>
    <br>
    <div  id="alvo" class="columns is-2">
        
        {% for pendencia in lista_pendencias_antigas %}
    
        <div class="columns is-2  ms-3">
            
            <div class="card ms-2" style="width: 19rem;">
                    <div  class="card-text p-1 mt-2 text-white " style="font-size: 20px; font-weight: 400; background-color:  rgba(0, 0, 0, 0.7);">Pendencia Nº {{ pendencia.pk }}</div>

                        <img src="{{ pendencia.thumb.url }}" class="card-img-top" style="height: 200px;"  alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ pendencia.list_maquina }}</h5>
                            <p class="card-text">{{ pendencia.corpo }}</p>
                        </div>
                            <ul class="list-group list-group-flush">
                            <li class="list-group-item">Tempo de manutenção: {{ pendencia.tempo_hora_homem }}</li>
                            <li class="list-group-item">Numero de orçamento: {{ pendencia.num_orcamento }}</li>
                            <li class="list-group-item">Data de Criação: {{ pendencia.data_criacao }}</li>
                            </ul>
                            
                                <div class="card">
                                    <footer class="card-footer">
                                      <a href="{% url 'gestor:detalhependencia' pendencia.pk %}" class="card-footer-item">Tratar Pendencia</a>
                                                                            
                                    </footer>
                            
                        
                    </div>
            </div>
        </div>
    
        <hr>{% endfor %}
        <br> 
    </div>
    <br>
</div>
<br>

    


{%endblock%}

gestor/templates/criarpend.html
{% extends 'visualizapendencias.html' %}
{% load crispy_forms_tags %}
{% block pendencias %}

<style>
    #alvo {
        display: flex;
        flex-wrap: nowrap;
        overflow-y: scroll;
        height: 700px;
      }   
</style>
<div class="container">
    

    <br>
    <div id="alvo" class="container">
<form method="post"> 
    {% csrf_token %} 
    {{form|crispy }} 
    <input type="submit" class="btn btn-outline-dark" value="Save"> 
    
</form></div> <br> <br>
</div> 
{% endblock %}

gestor/templates/detalhespendencias.html
{% extends 'visualizapendencias.html' %}


{% block  pendencias %}
<br>

    <div class="container">
      <br>
      <div class='container row p-2 text-white' style='background-color: #007982; font-weight: 500;'>
        <p class='h5'> Detalhes da Pendencia </p>             
    </div>
        <br>
        <div class='text-center'>
            <img src="{{ object.thumb.url }}" class="img-fluid rounded" style="height: 400px;" alt="...">
        </div>
        <br>
        <div class='card'>
            <h5 class="card-header border border-danger-subtle" style='font-weight: 500;'>{{ object.titulo }}</h5>
            <div class="card-body">
              <h5 class="card-title p-2 border-bottom border-info">Equipamento: {{object.list_maquina}}</h5>
              <p class="card-text p-2 border-bottom border-info-subtle">{{object.corpo}}</p>
              
              <p class="card-text p-2 border-bottom border-info-subtle">Pendencia foi gerada em : {{object.data_criacao}}</p>
              
              
              <p class="card-text p-2 border-bottom border-info-subtle">Tempo de manutenção : {{object.tempo_hora_homem}} horas</p>
              
              
              <p class="card-text p-2 border-bottom border-info-subtle">Esta pendencia encontra-se : {{object.status}}</p>
              
              <hr>
              <div class="card">
                <footer class="card-footer">
                  <a  onclick="NewTab()" class="btn btn-primary" type="button" 
                   
                  >Marcar pendencia como concluida</a>
                  
                
                </footer>
                <script>
                  function NewTab() {
                      window.open("{% url 'gestor:mudarstatus' object.pk %}",
                              "", "width=500, height=300");
                  }
                </script>
                
                
              </div>
              
                
            </div>
        </div>
        
        <div class='container'>
            <br>
            <p class='h4'> Tabela de materiais: </p>
        </div>
        <hr>
        <div>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">NI: </th>
                    <th scope="col">Material: </th>
                    <th scope="col">Quantidade: </th>
                    <th scope="col">Preço Final :</th>
                  </tr>
                </thead>
                <tbody>
                    {% for materiais in object.materiais.all %}
                  <tr>
                    <th scope="row">{{ materiais.ni}}</th>
                    <td>{{ materiais.item}}</td>
                    <td>{{ materiais.qtd}}</td>
                    <td>R$ {{ materiais.preco_final}}</td> 
                  </tr>
                    {% endfor %}
                </tbody>
              </table> 
              
              <br>
        </div>
        <div class='container'>
            <div class='container p-2 text-white' style='background-color: #007982; font-weight: 500;'>
                <p class='h5'> Demais pendencias no equipamento: {{object.list_maquina}}</p>   
                       
            </div>  <br>
            <br>

            <br> 

            <div class="columns is-2">
            
                {% for pend in pendencias_relacionadas %}  

                <div class="columns is-2  ms-3">

                    <div class="col">
                    <div class="ms-2" style="width: 20rem;">
                    <div  class="card-text p-2 text-white " style="font-size: 20px; font-weight: 400; background-color: #00a8b5;">Pendencia Nº {{ pend.pk }}</div>
                
                  <img src="{{ pend.thumb.url }}" class="card-img-top" style="height: 200px;" alt="...">
                  <div class="card-body border border-dark-subtle">
                    <h5 class="card-title">{{ pend.list_maquina }}</h5>
                    <p class="card-text">{{ pend.corpo }}</p>
                  </div>
                  <ul class="list-group list-group-flush border border-dark-subtle">
                    <li class="list-group-item">Tempo de manutenção: {{ pend.tempo_hora_homem }}</li>
                    <li class="list-group-item">Numero de orçamento: {{ pend.num_orcamento }}</li>
                    <li class="list-group-item">Data de Criação: {{ pend.data_criacao }}</li>
                  </ul>
                  <div class="card-body border border-dark-subtle">

                    <footer class="card-footer border border-dark-subtle">
                      <a href="{% url 'gestor:detalhependencia' pend.pk %}" class="card-footer-item">Tratar Pendencia</a>
                      <a href="#" class="card-footer-item">Orçamento Nº {{ pend.num_orcamento }}</a>
                      
                      </footer>


                      <div class="row">
                        <div class="col">
                         
                        </div>
                        <div class="col">
                          
                        </div>
                
                      </div>
                  </div>
                </div>
                  </div>
                  </div>
                  <hr>  
                {% endfor %}         
            </div>

        </div>

        <br>
    <br>

    </div>

{% endblock %}

gestor/templates/geral.html
{% extends 'visualizapendencias.html' %}


{% block  pendencias %}
<br>
<div class="container">
    

    <br>
    <div class= 'col'>
    <h1 class="title">Reimagine. Reinvente. Renove.</h1>
    <h2 class="subtitle">Gestor de Processos de Manutenção Automotiva</h2>
    </div>
    <br>
    
        <form class="d-flex" role="search" name= 'q' method="get" action="{% url 'gestor:pesquisa'%}">
            <input class="form-control me-2" type="search" name= 'q' placeholder="Procure por um equipametno..." aria-label="Search">
            <button class="btn btn-outline-success" type="submit" >Buscar</button>
        </form>
    



<hr>
</br>
<div class="row">

<div class="clearfix">
  {%  load static %}
  <img src="{% static 'images/logo_geral.jpg'%}" class="col-md-6 float-md-end mb-3 ms-md-3" style="height: 400px;" alt="...">

  <p class="has-text-justified"  style="font-weight: 400;">
    Bem-vindo à Recogitate: Soluções Inteligentes para Gestão de Manutenção Automotiva!   </p> <br>

  <p class="has-text-justified">
    Nós, na Recogitate, entendemos a importância da gestão eficiente da manutenção automotiva para garantir a confiabilidade e o desempenho otimizado da sua frota de veículos. Com vasta experiência no setor, oferecemos soluções inteligentes e inovadoras que permitem que sua empresa alcance níveis excepcionais de eficiência operacional.    <br></p> <br>
  <p class="has-text-justified">
    Nosso foco principal está no controle de backlog e no controle de componentes, dois aspectos fundamentais da gestão de manutenção automotiva. O backlog, representado por tarefas de manutenção pendentes, pode se acumular rapidamente, resultando em atrasos, interrupções operacionais e custos adicionais. Com a nossa abordagem estruturada e ferramentas avançadas, ajudamos a sua empresa a gerenciar e reduzir o backlog, garantindo que a manutenção seja realizada de forma oportuna e eficaz.  </p><br>
  <p class="has-text-justified">
    Além disso, o controle de componentes é uma parte essencial da gestão da manutenção automotiva. Sabemos que peças e componentes desgastados ou em mau estado podem afetar negativamente o desempenho e a segurança dos veículos. Com nossas soluções especializadas, oferecemos um sistema abrangente de controle de componentes, permitindo que você acompanhe o status de cada item, realize manutenção preventiva e evite falhas inesperadas.  </p><br>
  <p class="has-text-justified">
    Na Recogitate, acreditamos no poder da tecnologia para impulsionar a excelência operacional. Nossas soluções são baseadas em plataformas avançadas e intuitivas, que oferecem recursos de rastreamento, programação, análise de dados e geração de relatórios personalizados. Dessa forma, você terá uma visão abrangente e em tempo real do estado da sua frota, permitindo que tome decisões informadas e estratégicas.  </p><br>
  <p class="has-text-justified">
    Nossa equipe altamente qualificada está pronta para ajudar sua empresa a otimizar a gestão da manutenção automotiva. Combinando conhecimento técnico, experiência prática e um compromisso inabalável com a satisfação do cliente, estamos prontos para ser seu parceiro confiável nessa jornada.  </p><br>
    <p class="has-text-justified" >
      Entre em contato conosco hoje mesmo e descubra como a Recogitate pode transformar sua gestão de manutenção automotiva, trazendo eficiência, economia e confiabilidade para sua frota de veículos. Juntos, alcançaremos novos patamares de sucesso!
    </p>

 
</div>
          
      <div class="container">
          
      </div>
      <div class="container">
          <br>
          <hr>
          <p class="has-text-justified" >
          </p>
          <br>
      </div>



</div>

<br>
</div>
<br>



{% endblock %}

gestor/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<header class="masthead">
  <!-- Intro settings -->
  <style>
    /* Default height for small devices */
    #intro-example {
      height: 1000px;
    }

    /* Height for devices larger than 992px */
    @media (min-width: 992px) {
      #intro-example {
        height: 788px;
      }
    }
  </style>

  {%  load static %}

  <!-- Background image -->
  <div id="intro-example" class="p-5 text-center bg-image"  style="background-image: url('{% static 'images/maquinas.jpg'%}')";>
    
  
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.7);">

      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <p class="mb-3 h2 p-2">Login<p><br>
          
          <form method='post'>
            
            <fildset>
              <legend class="mb-4 h5">Preencha os dados para executar o login:</legend>
              {{form|crispy }}
            </fildeset><br>
          <button
            class="btn btn-outline-light  m-2"
            href="{% url 'gestor:login' %}"
            role="button"
            rel="nofollow"
            type="submit"
            target="_blank">Login</button><br>
          </form>
         
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>

{% endblock %}

gestor/templates/logout.html
{% extends 'base.html' %}

{% block content %}
<header class="masthead">
  <!-- Intro settings -->
  <style>
    /* Default height for small devices */
    #intro-example {
      height: 1000px;
    }

    /* Height for devices larger than 992px */
    @media (min-width: 992px) {
      #intro-example {
        height: 788px;
      }
    }
  </style>

  

  <!-- Background image -->
  <div
  {
    text-align: center;
  }
    id="intro-example"
    class="p-5 text-center bg-image"
    {%  load static %}
    style="background-image: url('{% static 'images/maquinas.jpg'%} '); align="center";

    
  
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.7);">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3 p-1">Você acaba de sair de sua conta</h1>
          <h5 class="mb-4"></h5>
          <a
            class="btn btn-outline-light btn-lg m-2"
            href="{% url 'gestor:login' %}"
            role="button"
            rel="nofollow"
            target="_blank"
          >Login</a
          >
          <a
            class="btn btn-outline-light btn-lg m-2"
            href="{% url 'gestor:home' %}"
            target="_blank"
            role="button"
          >Inicio</a
          >
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>

{% endblock %}

gestor/templates/main.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{%endblock%}

gestor/templates/recentes.html
{% extends 'visualizapendencias.html' %}

{% block pendencias %}
<style>
    #alvo {
        display: flex;
        flex-wrap: nowrap;
        overflow-x: scroll;
        width: 1200px;
      }   
</style>
<div class="container">
    <br>
    <br>
    <div  id="alvo" class="columns is-2">
        
        {% for pendencia in lista_pendencias_recentes %}
    
        <div class="columns is-2  ms-3">
            
            <div class="card ms-2" style="width: 19rem;">
                    <div  class="card-text p-1 mt-2 text-white " style="font-size: 20px; font-weight: 400; background-color:  rgba(0, 0, 0, 0.7);">Pendencia Nº {{ pendencia.pk }}</div>

                        <img src="{{ pendencia.thumb.url }}" class="card-img-top" style="height: 200px;"  alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ pendencia.list_maquina }}</h5>
                            <p class="card-text">{{ pendencia.corpo }}</p>
                        </div>
                            <ul class="list-group list-group-flush">
                            <li class="list-group-item">Tempo de manutenção: {{ pendencia.tempo_hora_homem }}</li>
                            <li class="list-group-item">Numero de orçamento: {{ pendencia.num_orcamento }}</li>
                            <li class="list-group-item">Data de Criação: {{ pendencia.data_criacao }}</li>
                            </ul>
                            
                                <div class="card">
                                    <footer class="card-footer">
                                      <a href="{% url 'gestor:detalhependencia' pendencia.pk %}" class="card-footer-item">Tratar Pendencia</a>
                                                                            
                                    </footer>
                            
                        
                    </div>
            </div>
        </div>
    
        <hr>{% endfor %}
        <br> 
    </div>
    <br>
</div>
<br>

    


{%endblock%}

gestor/templates/vencidos.html
{% extends 'visualizapendencias.html' %}

{% block pendencias %}
<style>
    #alvo {
        display: flex;
        flex-wrap: nowrap;
        overflow-x: scroll;
        width: 1200px;
      }   
</style>
<div class="container">
    <br>
    <br>
    <div  id="alvo" class="columns is-2">
        
        {% for pendencia in lista_pendencias_vencidas %}
    
        <div class="columns is-2  ms-3">
            
            <div class="card ms-2" style="width: 19rem;">
                    <div  class="card-text p-1 mt-2 text-white " style="font-size: 20px; font-weight: 400; background-color:  rgba(0, 0, 0, 0.7);">Pendencia Nº {{ pendencia.pk }}</div>

                        <img src="{{ pendencia.thumb.url }}" class="card-img-top" style="height: 200px;"  alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ pendencia.list_maquina }}</h5>
                            <p class="card-text">{{ pendencia.corpo }}</p>
                        </div>
                            <ul class="list-group list-group-flush">
                            <li class="list-group-item">Tempo de manutenção: {{ pendencia.tempo_hora_homem }}</li>
                            <li class="list-group-item">Numero de orçamento: {{ pendencia.num_orcamento }}</li>
                            <li class="list-group-item">Data de Criação: {{ pendencia.data_criacao }}</li>
                            </ul>
                            
                                <div class="card">
                                    <footer class="card-footer">
                                      <a href="{% url 'gestor:detalhependencia' pendencia.pk %}" class="card-footer-item">Tratar Pendencia</a>
                                                                            
                                    </footer>
                            
                        
                    </div>
            </div>
        </div>
    
        <hr>{% endfor %}
        <br> 
    </div>
    <br>
</div>
<br>

    


{%endblock%}

gestor/templates/visualizapendencias.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container ">
    <div class="columns is-variable is-1-mobile is-0-tablet is-3-desktop is-8-widescreen is-2-fullhd">
        <div class="column is-one-quarter ">
            <aside class="menu">
            <p class="menu-label">
            Gestão de Backlogs
            </p>
            <ul class="menu-list">
            <li><a href="{% url 'gestor:geral'%}">Visão Geral</a></li>
           
            </ul>
            <p class="menu-label">
            Administração
            </p>
            <ul class="menu-list">
            
            <li>
                <a class="is-active" style="background-color: rgba(0, 0, 0, 0.6); ">Gerenciar Pendencias</a>
                <ul>
                <li><a href="{% url 'gestor:painel'%}">Painel</a></li>
                <li><a href="{% url 'gestor:backlog'%}">Pendencias Recentes</a></li>
                <li><a href="{% url 'gestor:atrasados'%}">Pendencias Antigas</a></li>
                <li><a href="{% url 'gestor:vencidos'%}">Itens vencidos</a></li>
                <li><a href="{% url 'gestor:criarpend'%}">Add Pendencias</a></li>
                </ul>
            </li>
            </ul>
            <p class="menu-label">
            Materiais
            </p>
            <ul class="menu-list">
            <li><a href="{% url 'gestor:addcusto'%}">Adicionar materiais</a></li>
            </ul>
            </aside>
        </div>

        <div class="columns">

            

            {% block pendencias %}
            {% endblock %}

        </div>
    </div>

</div>
{%endblock%}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(0, 0, 0, 0.9); " >
    <div class="container-fluid">
      <a class="navbar-brand" href="/" style="font-size: 24px; font-weight: 800;">Recogitate</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link "  href="{% url 'gestor:geral'%}" style="font-size: 20px; font-weight: 600;">Gestão de Pendencias</a>
          </li>
          {% else %}
          <li class="nav-item ">
            <a class="nav-link "  href="#" style="font-size: 20px; font-weight: 600;">Contato</a>
          </li>
          {% endif %} 
  
  
  
        </ul>
        <ul class="d-flex navbar-nav">
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gestor:logout'%}" style="font-size: 20px; font-weight: 600;">Logout</a>
              </li>
              
          {% endif %}
          </ul>
  
  
      </div>
    </div>
  </nav>